server:
  port: 9002

spring:
  application:
    name: consumer

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.0:3306/homework?characterEncoding=utf8
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/

